//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOVOICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debate
    {
        public long id { get; set; }
        public string listname { get; set; }
        public string areaelection { get; set; }
        public string time { get; set; }
        public string description { get; set; }
    }
}
