//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOVOICE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionEntities : DbContext
    {
        public ElectionEntities()
            : base("name=ElectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Debate> Debates { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<LocalCandidate> LocalCandidates { get; set; }
        public virtual DbSet<LocalList> LocalLists { get; set; }
        public virtual DbSet<PartyCandidate> PartyCandidates { get; set; }
        public virtual DbSet<PartyList> PartyLists { get; set; }
        public virtual DbSet<paymentnew> paymentnews { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TempAd> TempAds { get; set; }
        public virtual DbSet<TempCandidateLocal> TempCandidateLocals { get; set; }
        public virtual DbSet<TempDebate> TempDebates { get; set; }
        public virtual DbSet<TempPartyCandidate> TempPartyCandidates { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
