//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOVOICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCandidateLocal
    {
        public long id { get; set; }
        public Nullable<long> national_id { get; set; }
        public string name { get; set; }
        public string listname { get; set; }
        public string type_of_chair { get; set; }
        public string gender { get; set; }
        public string birthdate { get; set; }
        public Nullable<long> votes_counter { get; set; }
        public string religion { get; set; }
        public Nullable<long> fk_admin { get; set; }
        public string electionarea { get; set; }
        public string city { get; set; }
        public string email { get; set; }
    }



    public class TempCandidateLocalsViewModel
    {
        public string ElectionArea { get; set; }
        public string City { get; set; }
        public string ListName { get; set; }
        public int MaxCandidates { get; set; }
        public List<TempCandidateLocal> Candidates { get; set; }

        public TempCandidateLocalsViewModel()
        {
            Candidates = new List<TempCandidateLocal>(10);
            for (int i = 0; i < 10; i++)
            {
                Candidates.Add(new TempCandidateLocal());
            }
        }
    }

}
