//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOVOICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempPartyCandidate
    {
        public long id { get; set; }
        public Nullable<long> national_id { get; set; }
        public string electionarea { get; set; }
        public string email { get; set; }
        public string partyname { get; set; }
        public string gender { get; set; }
        public string birthdate { get; set; }
        public string religion { get; set; }
        public Nullable<long> ordercandidate { get; set; }
        public string candidatename { get; set; }
        public Nullable<long> fk_admin { get; set; }
        public string city { get; set; }
    }

    public class TempPartyCandidateViewModel
    {
        public List<TempPartyCandidate> Candidates { get; set; }
        public string ElectionArea { get; set; }
        public string City { get; set; }
        public string PartyName { get; set; }

        public TempPartyCandidateViewModel()
        {
            Candidates = new List<TempPartyCandidate>(41); // Initialize with 41 empty candidates
            for (int i = 0; i < 41; i++)
            {
                Candidates.Add(new TempPartyCandidate());
            }
        }
    }
}
